name: WRITE
'on':
  repository_dispatch:
    types:
    - write_file
jobs:
  write:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Write placeholder
      run: echo write
